# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
