# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='allowed_programs',
            field=models.ManyToManyField(related_name='licenses', to='software.Program'),
        ),
        migrations.AddField(
            model_name='version',
            name='allowed_licenses',
            field=models.ManyToManyField(related_name='versions', to='software.License'),
        ),
    ]
